In [1]:
%matplotlib inline
import os
os.environ['PY3_PROD'] = '1'
%load_ext autoreload
%autoreload 2
os.system('kinit')

1

In [25]:
import numpy as np
import math
import pandas as pd
from typing import Union, List
import datetime
from pycmqlib3.utility import misc
import pycmqlib3.analytics.data_handler as dh
import pathlib
from pycmqlib3.utility.process_wt_data import *
from pycmqlib3.utility import dataseries

In [10]:
# xdf = load_fut_by_product('cs', 'DCE', datetime.date(2020,1,1), datetime.date(2022,10,28), freq='d')
# xdf
xdf = dataseries.load_processed_fut_by_product('cs', start_date=datetime.date(2020,1,1), end_date=datetime.date(2022,10,28), freq = 'd',
                                  roll_win=3, roll_cutoff='-20b', cont_ratio=[1.0, 1.0],
                                  contract_filter=None, min_thres=0)
xdf

,instID,date,open,high,low,close,volume,openInterest,expiry,exp_str,month,roll_date,roll_ind,log_ret,price_chg
10,cs2003,2020-01-10,2156.0,2156.0,2156.0,2156.0,1.0,4.0,2020-03-13,2020-03-13,3,2020-02-14,6.000000,0.000000,0.0
11,cs2003,2020-01-14,2237.0,2237.0,2237.0,2237.0,1.0,4.0,2020-03-13,2020-03-13,3,2020-02-14,6.000000,0.036881,81.0
12,cs2003,2020-01-15,2230.0,2230.0,2220.0,2220.0,3.0,5.0,2020-03-13,2020-03-13,3,2020-02-14,6.000000,-0.007628,-17.0
13,cs2003,2020-01-16,2255.0,2255.0,2255.0,2255.0,1.0,6.0,2020-03-13,2020-03-13,3,2020-02-14,6.666667,0.015643,35.0
14,cs2003,2020-01-21,2206.0,2257.0,2206.0,2257.0,2.0,7.0,2020-03-13,2020-03-13,3,2020-02-14,8.000000,0.000887,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3750,cs2309,2022-10-21,3348.0,3361.0,3340.0,3354.0,239.0,1052.0,2023-09-14,2023-09-14,9,2023-08-17,1377.000000,0.000298,1.0
3751,cs2309,2022-10-24,3354.0,3369.0,3338.0,3350.0,677.0,1234.0,2023-09-14,2023-09-14,9,2023-08-17,1475.000000,-0.001193,-4.0
3752,cs2309,2022-10-25,3346.0,3348.0,3283.0,3287.0,1017.0,1229.0,2023-09-14,2023-09-14,9,2023-08-17,1816.000000,-0.018985,-63.0
3753,cs2309,2022-10-27,3251.0,3280.0,3239.0,3267.0,473.0,1316.0,2023-09-14,2023-09-14,9,2023-08-17,1982.000000,-0.006103,-20.0
3754,cs2309,2022-10-28,3269.0,3278.0,3232.0,3255.0,287.0,1305.0,2023-09-14,2023-09-14,9,2023-08-17,1875.666667,-0.003680,-12.0

In [27]:
load_bars_to_df('i2301', d_start = datetime.date(2022,6,1), d_end=datetime.date(2022,10,31), freq = 'm1', index_col=None)

,instID,datetime,date,min_id,open,high,low,close,volume,openInterest
0,i2301,2022-05-31 21:01:00,2022-06-01,301,825.5,827.5,825.5,827.5,703.0,174306.0
1,i2301,2022-05-31 21:02:00,2022-06-01,302,827.5,827.5,826.0,826.5,560.0,174482.0
2,i2301,2022-05-31 21:03:00,2022-06-01,303,826.5,826.5,824.5,826.0,700.0,174579.0
3,i2301,2022-05-31 21:04:00,2022-06-01,304,826.5,828.0,826.0,827.0,662.0,174690.0
4,i2301,2022-05-31 21:05:00,2022-06-01,305,827.0,829.0,827.0,828.0,800.0,174610.0
...,...,...,...,...,...,...,...,...,...,...
34525,i2301,2022-10-31 14:55:00,2022-10-31,2055,604.0,604.5,603.0,603.5,2854.0,770207.0
34526,i2301,2022-10-31 14:56:00,2022-10-31,2056,603.5,604.0,602.5,604.0,4002.0,770684.0
34527,i2301,2022-10-31 14:57:00,2022-10-31,2057,603.5,605.5,603.5,605.5,6338.0,768958.0
34528,i2301,2022-10-31 14:58:00,2022-10-31,2058,605.5,606.0,605.0,605.5,4780.0,767771.0
34529,i2301,2022-10-31 14:59:00,2022-10-31,2059,605.5,607.0,605.0,606.5,8216.0,765792.0

In [40]:
start_date = datetime.date(2019,1,1)
end_date = datetime.date(2022,10,27)
folder_loc='C:/dev/wtdev/storage/his'
dtHelper = WtDataHelper()
product='cs'
freq = 'm5'
period = 'day'
if freq in ['m', 'm1']:
    freq = 'm1'
    period = 'min1'
elif freq in ['m5']:
    period = 'min5'
if product == 'MA':
    prod_keys = ['ME', 'MA']
elif product == 'ZC':
    prod_keys = ['TC', 'ZC']
else:
    prod_keys = [product]
exch = misc.prod2exch(product)
out_df = pd.DataFrame()
src_path = '%s/%s/%s' % (folder_loc, period, exch)
file_list = [f for f in listdir(src_path) if isfile(join(src_path, f))]
for file in file_list:
    cont = file.split('.')[0]
    prod = cont[:2] if exch in ['CZCE',] else cont[:-4]
    if prod not in prod_keys:
        continue
    dst_df = dtHelper.read_dsb_bars(f'{src_path}/{file}')
    if dst_df:
        dst_df = dst_df.to_df()
        dst_df = dst_df.rename(columns = {'hold': 'openInterest'})
    else:
        continue
    dst_df = convert_wt_data(dst_df, cont, freq = freq)
    out_df = out_df.append(dst_df)

In [41]:
out_df

,instID,datetime,date,min_id,open,high,low,close,volume,openInterest
201412190905,cs1503,2014-12-19 09:05:00,2014-12-19,1505,2750.0,2754.0,2686.0,2754.0,6.0,8.0
201412190910,cs1503,2014-12-19 09:10:00,2014-12-19,1510,2754.0,2755.0,2754.0,2755.0,8.0,12.0
201412190915,cs1503,2014-12-19 09:15:00,2014-12-19,1515,2755.0,2755.0,2754.0,2755.0,38.0,46.0
201412190920,cs1503,2014-12-19 09:20:00,2014-12-19,1520,2755.0,2755.0,2755.0,2755.0,62.0,108.0
201412190940,cs1503,2014-12-19 09:40:00,2014-12-19,1540,2754.0,2754.0,2754.0,2754.0,2.0,110.0
...,...,...,...,...,...,...,...,...,...,...
202210311440,cs2309,2022-10-31 14:40:00,2022-10-31,2040,3241.0,3241.0,3238.0,3238.0,1.0,1335.0
202210311445,cs2309,2022-10-31 14:45:00,2022-10-31,2045,3238.0,3238.0,3238.0,3238.0,0.0,1335.0
202210311450,cs2309,2022-10-31 14:50:00,2022-10-31,2050,3238.0,3243.0,3238.0,3243.0,1.0,1336.0
202210311455,cs2309,2022-10-31 14:55:00,2022-10-31,2055,3243.0,3243.0,3238.0,3239.0,3.0,1334.0
202210311500,cs2309,2022-10-31 15:00:00,2022-10-31,2100,3239.0,3244.0,3238.0,3244.0,10.0,1330.0

In [ ]:
def load_fut_by_product(product, exch, start_date, end_date, freq = 'd', folder_loc='C:/dev/wtdev/storage/his'):
    if end_date is None:
        end_date = datetime.date.today()
        end_time = 
    if start_date is None:
        start_date = end_date - datetime.timedelta(days=365)
    period = 'day'
    if freq in ['m', 'm1']:
        freq = 'm1'
        period = 'min1'
    elif freq in ['m5']:
        period = 'min5'
    if product == 'MA':
        prod_keys = ['ME', 'MA']
    elif product == 'ZC':
        prod_keys = ['TC', 'ZC']
    else:
        prod_keys = [product]
    exch = prod2exch(product)
    out_df = pd.DataFrame()
    src_path = '%s/%s/%s' % (folder_loc, period, exch)
    cont_list = [ cont[:2] if exch in ['CZCE',] else cont[:-4] for cont in cont_list]
    for file in file_list:
        cont = file.split('.')[0]
        prod = cont[:2] if exch in ['CZCE',] else cont[:-4]
        if prod not in prod_keys:
            continue
        dst_df = dtHelper.read_dsb_bars(f'{src_path}/{file}')

In [4]:
from wtpy import WtDtServo

dtServo = WtDtServo()
dtServo.setBasefiles(folder="../common/")
dtServo.setStorage(path='../storage/')

In [8]:
bars = dtServo.get_bars("INE.sc2112", "m5", fromTime=201905010930, endTime=202212301500).to_df()
bars

,date,bartime,open,high,low,close,settle,money,volume,hold,diff
2905101000,20190510,2905101000,451.3,451.3,451.3,451.3,0.0,902600.0,2.0,18.0,0.0
2905101355,20190510,2905101355,451.3,462.0,451.3,462.0,0.0,924000.0,2.0,18.0,0.0
2905211430,20190521,2905211430,464.9,464.9,464.3,464.3,0.0,928600.0,2.0,18.0,0.0
2905242105,20190527,2905242105,459.9,459.9,459.9,459.9,0.0,919800.0,2.0,18.0,0.0
2905270905,20190527,2905270905,459.9,459.9,459.9,459.9,0.0,919800.0,2.0,18.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3111270200,20211129,3111270200,497.2,497.2,497.2,497.2,0.0,497200.0,1.0,1162.0,0.0
3111290925,20211129,3111290925,495.0,495.0,495.0,495.0,0.0,495000.0,1.0,1161.0,-1.0
3111300905,20211130,3111300905,451.9,451.9,451.9,451.9,0.0,451900.0,1.0,1161.0,0.0
3111301035,20211130,3111301035,462.9,462.9,462.9,462.9,0.0,462900.0,1.0,1161.0,0.0
3111301055,20211130,3111301055,462.9,462.9,456.8,456.8,0.0,456800.0,1.0,1161.0,0.0

In [11]:
bars['bartime'] = bars['bartime'] + 9000000000
bars

,date,bartime,open,high,low,close,settle,money,volume,hold,diff
2905101000,20190510,201905101000,451.3,451.3,451.3,451.3,0.0,902600.0,2.0,18.0,0.0
2905101355,20190510,201905101355,451.3,462.0,451.3,462.0,0.0,924000.0,2.0,18.0,0.0
2905211430,20190521,201905211430,464.9,464.9,464.3,464.3,0.0,928600.0,2.0,18.0,0.0
2905242105,20190527,201905242105,459.9,459.9,459.9,459.9,0.0,919800.0,2.0,18.0,0.0
2905270905,20190527,201905270905,459.9,459.9,459.9,459.9,0.0,919800.0,2.0,18.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3111270200,20211129,202111270200,497.2,497.2,497.2,497.2,0.0,497200.0,1.0,1162.0,0.0
3111290925,20211129,202111290925,495.0,495.0,495.0,495.0,0.0,495000.0,1.0,1161.0,-1.0
3111300905,20211130,202111300905,451.9,451.9,451.9,451.9,0.0,451900.0,1.0,1161.0,0.0
3111301035,20211130,202111301035,462.9,462.9,462.9,462.9,0.0,462900.0,1.0,1161.0,0.0
3111301055,20211130,202111301055,462.9,462.9,456.8,456.8,0.0,456800.0,1.0,1161.0,0.0

In [19]:
start_date = datetime.date(2000,1,1)
end_date = datetime.date(2022,10,25)
src_folder = 'c:/dev/data/his'
dst_folder = 'C:/dev/wtdev/storage/his'
target_folder = 'C:/dev/wtdev/FUT_Data/his'
cutoff_date = 20221024

combine_bars_wt_store(src_folder=src_folder,
                        dst_folder=dst_folder,
                        target_folder=target_folder,
                        cutoff=cutoff_date)

day-CFFEX
day-DCE
day-CZCE
day-SHFE
day-INE
min1-CFFEX
min1-DCE
min1-CZCE
min1-SHFE
min1-INE
min5-CFFEX
min5-DCE
min5-CZCE
min5-SHFE
min5-INE

In [38]:
from os import listdir
from os.path import isfile, join
mypath = 'C:/dev/data/his/day/CFFEX'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
print(onlyfiles)

['IC2208.dsb', 'IC2209.dsb', 'IC2210.dsb', 'IC2211.dsb', 'IC2212.dsb', 'IC2303.dsb', 'IF2208.dsb', 'IF2209.dsb', 'IF2210.dsb', 'IF2211.dsb', 'IF2212.dsb', 'IF2303.dsb', 'IH2208.dsb', 'IH2209.dsb', 'IH2210.dsb', 'IH2211.dsb', 'IH2212.dsb', 'IH2303.dsb', 'IM2208.dsb', 'IM2209.dsb', 'IM2210.dsb', 'IM2211.dsb', 'IM2212.dsb', 'IM2303.dsb', 'T2209.dsb', 'T2212.dsb', 'T2303.dsb', 'T2306.dsb', 'TF2209.dsb', 'TF2212.dsb', 'TF2303.dsb', 'TF2306.dsb', 'TS2209.dsb', 'TS2212.dsb', 'TS2303.dsb', 'TS2306.dsb']

In [22]:
bars = dtServo.get_bars("DCE.c2301", "m1", fromTime=202205010930, endTime=202210211500).to_df()
bars

,date,bartime,open,high,low,close,settle,money,volume,hold,diff
3205050902,20220505,3205050902,3013.0,3017.0,3013.0,3015.0,0.0,672345.0,223.0,86755.0,144.0
3205050903,20220505,3205050903,3015.0,3021.0,3015.0,3020.0,0.0,1534160.0,508.0,86971.0,216.0
3205050904,20220505,3205050904,3021.0,3021.0,3018.0,3019.0,0.0,667199.0,221.0,86877.0,-94.0
3205050905,20220505,3205050905,3019.0,3019.0,3015.0,3015.0,0.0,621090.0,206.0,86771.0,-106.0
3205050906,20220505,3205050906,3016.0,3016.0,3013.0,3013.0,0.0,620678.0,206.0,86814.0,43.0
...,...,...,...,...,...,...,...,...,...,...,...
3210211456,20221021,3210211456,2878.0,2878.0,2877.0,2877.0,0.0,29639780.0,1030.0,708906.0,135.0
3210211457,20221021,3210211457,2878.0,2879.0,2877.0,2878.0,0.0,37904500.0,1317.0,708684.0,-222.0
3210211458,20221021,3210211458,2879.0,2879.0,2877.0,2878.0,0.0,60759610.0,2111.0,707834.0,-850.0
3210211459,20221021,3210211459,2877.0,2879.0,2877.0,2878.0,0.0,63436470.0,2204.0,707392.0,-442.0
3210211500,20221021,3210211500,2878.0,2879.0,2876.0,2878.0,0.0,73316550.0,2548.0,706731.0,-661.0

In [48]:
ret = dtHelper.resample_bars("../storage/his/day/CFFEX/IF2209.dsb",'min1',5,200908120931,202210021500,sInfo)
print(ret.to_df())

AttributeError: 'NoneType' object has no attribute 'to_df'

In [22]:
# dtHelper = WtDataHelper()
# sessMgr = SessionMgr()
# sessMgr.load("../common/sessions.json")
# sInfo = sessMgr.getSession("SD0930")

res = dtHelper.read_dsb_bars("C:/dev/wtdev/storage/his/min5/DCE/i2101.dsb")
#res = dtHelper.read_dsb_bars("C:/dev/data/his/min1/INE/bc2301.dsb")
rdf = res.to_df()
print(rdf[rdf.date<20221025])

                  date       bartime    open    high     low   close  settle  \
202001172300  20200120  202001172300   589.0   589.0   589.0   589.0     0.0
202001200905  20200120  202001200905   589.0   590.0   587.5   589.0     0.0
202001200910  20200120  202001200910   589.0   589.5   588.5   589.0     0.0
202001200915  20200120  202001200915   589.0   589.0   588.0   588.0     0.0
202001200920  20200120  202001200920   588.0   589.5   587.5   589.5     0.0
...                ...           ...     ...     ...     ...     ...     ...
202101141450  20210114  202101141450  1149.0  1150.0  1149.0  1150.0     0.0
202101141500  20210114  202101141500  1149.0  1149.0  1149.0  1149.0     0.0
202101142105  20210115  202101142105  1149.0  1149.0  1140.0  1140.0     0.0
202101150910  20210115  202101150910  1157.0  1157.0  1157.0  1157.0     0.0
202101151035  20210115  202101151035  1158.0  1160.0  1158.0  1160.0     0.0

                   money  volume    hold   diff
202001172300  36694700.0   623.0  5388.0    0.0
202001200905   2061500.0    35.0  5392.0    4.0
202001200910   2650500.0    45.0  5378.0  -14.0
202001200915   3234000.0    55.0  5405.0   27.0
202001200920   3419100.0    58.0  5395.0  -10.0
...                  ...     ...     ...    ...
202101141450   6785000.0    59.0  6817.0    0.0
202101141500  22980000.0   200.0  6817.0    0.0
202101142105  11400000.0   100.0  6717.0 -100.0
202101150910    115700.0     1.0  6716.0   -1.0
202101151035    580000.0     5.0  6711.0   -5.0

[14508 rows x 11 columns]

,date,bartime,open,high,low,close,settle,money,volume,hold,diff
202109142101,20210915,202109142101,2515.0,2520.0,2515.0,2515.0,0.0,226350.0,9.0,9.0,0.0
202109142102,20210915,202109142102,2520.0,2520.0,2520.0,2520.0,0.0,25200.0,1.0,10.0,1.0
202109142104,20210915,202109142104,2520.0,2520.0,2519.0,2519.0,0.0,25190.0,1.0,10.0,0.0
202109142107,20210915,202109142107,2519.0,2519.0,2519.0,2519.0,0.0,50380.0,2.0,10.0,0.0
202109142109,20210915,202109142109,2519.0,2520.0,2519.0,2520.0,0.0,50400.0,2.0,12.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
202209151448,20220915,202209151448,2775.0,2775.0,2775.0,2775.0,0.0,0.0,0.0,4499.0,0.0
202209151451,20220915,202209151451,2775.0,2775.0,2775.0,2775.0,0.0,0.0,0.0,4499.0,0.0
202209151453,20220915,202209151453,2775.0,2775.0,2775.0,2775.0,0.0,0.0,0.0,4499.0,0.0
202209151455,20220915,202209151455,2775.0,2775.0,2775.0,2775.0,0.0,0.0,0.0,4499.0,0.0
202209151456,20220915,202209151456,2775.0,2775.0,2775.0,2775.0,0.0,0.0,0.0,4499.0,0.0

In [ ]:
res = dtHelper.read_dsb_bars("C:/dev/data/his/day/INE/sc2212.dsb")
#res = dtHelper.read_dsb_bars("./i2209.dsb")
rdf = res.to_df()
print(rdf)

In [37]:
res = dtHelper.read_dsb_ticks("C:/dev/data/his_new/DCE/20220831/c2301.dsb")
rdf = res.to_df()
print(rdf)

                    time exchg   code   price    open    high     low  \
0      20220830210000476   DCE  c2301  2782.0  2788.0  2788.0  2778.0
1      20220830210000980   DCE  c2301  2782.0  2788.0  2788.0  2778.0
2      20220830210001464   DCE  c2301  2781.0  2788.0  2788.0  2778.0
3      20220830210001972   DCE  c2301  2782.0  2788.0  2788.0  2778.0
4      20220830210002476   DCE  c2301  2781.0  2788.0  2788.0  2778.0
...                  ...   ...    ...     ...     ...     ...     ...
31372  20220831145957736   DCE  c2301  2797.0  2788.0  2807.0  2772.0
31373  20220831145958528   DCE  c2301  2797.0  2788.0  2807.0  2772.0
31374  20220831145958952   DCE  c2301  2796.0  2788.0  2807.0  2772.0
31375  20220831145959160   DCE  c2301  2797.0  2788.0  2807.0  2772.0
31376  20220831145959912   DCE  c2301  2797.0  2788.0  2807.0  2772.0

       settle_price  upper_limit  lower_limit  ...  ask_qty_0  ask_qty_1  \
0               0.0          0.0          0.0  ...       32.0        0.0
1               0.0          0.0          0.0  ...       74.0        0.0
2               0.0          0.0          0.0  ...        3.0        0.0
3               0.0          0.0          0.0  ...       98.0        0.0
4               0.0          0.0          0.0  ...      126.0        0.0
...             ...          ...          ...  ...        ...        ...
31372           0.0          0.0          0.0  ...      395.0        0.0
31373           0.0          0.0          0.0  ...      396.0        0.0
31374           0.0          0.0          0.0  ...      396.0        0.0
31375           0.0          0.0          0.0  ...      395.0        0.0
31376        2789.0          0.0          0.0  ...      395.0        0.0

       ask_qty_2  ask_qty_3  ask_qty_4  ask_qty_5  ask_qty_6  ask_qty_7  \
0            0.0        0.0        0.0        0.0        0.0        0.0
1            0.0        0.0        0.0        0.0        0.0        0.0
2            0.0        0.0        0.0        0.0        0.0        0.0
3            0.0        0.0        0.0        0.0        0.0        0.0
4            0.0        0.0        0.0        0.0        0.0        0.0
...          ...        ...        ...        ...        ...        ...
31372        0.0        0.0        0.0        0.0        0.0        0.0
31373        0.0        0.0        0.0        0.0        0.0        0.0
31374        0.0        0.0        0.0        0.0        0.0        0.0
31375        0.0        0.0        0.0        0.0        0.0        0.0
31376        0.0        0.0        0.0        0.0        0.0        0.0

       ask_qty_8  ask_qty_9
0            0.0        0.0
1            0.0        0.0
2            0.0        0.0
3            0.0        0.0
4            0.0        0.0
...          ...        ...
31372        0.0        0.0
31373        0.0        0.0
31374        0.0        0.0
31375        0.0        0.0
31376        0.0        0.0

[31377 rows x 62 columns]

In [4]:
import datetime
from pycmqlib3.utility import misc
tday = datetime.date.today()
now = datetime.datetime.now()
print(now.hour)

1

In [13]:

def get_run_date():
    tday = datetime.date.today()
    now = datetime.datetime.now()
    if misc.is_workday(tday, 'CHN') and now.hour < 18:
        run_date = tday
    else:
        run_date = misc.day_shift(tday, '1b', misc.CHN_Holidays)
    return run_date
rdate = get_run_date()
rdate.strftime('%Y%m%d')

'20220819'

In [36]:
df = pd.read_csv('C:/dev/data/daily_data_220903a.csv', header = None)
print(df)
df.columns = ['instID', 'exch', 'date', 'open', 'high', 'low', 'close', 'settle', 'vol', 'hold']

df['date'] = df['date'].astype('datetime64').dt.strftime('%Y%m%d').astype('int64')
#df['time'] = (df['date']-19900000)*10000 + df['time'].str.replace(':', '').str[:-2].astype('int')
df['time'] = 199000000000
BUFFER = WTSBarStruct*len(df)
buffer = BUFFER()

def assign(procession, buffer):
    tuple(map(lambda x: setattr(buffer[x[0]], procession.name, x[1]), enumerate(procession)))


df.apply(assign, buffer=buffer)
print(df)
print(buffer[0].to_dict)
print(buffer[-1].to_dict)

dtHelper.store_bars(barFile="./test.bin", firstBar=buffer, count=len(df), period="d")

           0     1           2        3        4        5        6  \
0      a2209   DCE  2022-08-29   5944.0   5990.0   5933.0   5975.0
1      a2209   DCE  2022-08-30   5963.0   6002.0   5962.0   5969.0
2      a2209   DCE  2022-08-31   5980.0   5980.0   5900.0   5900.0
3      a2209   DCE  2022-09-01   5899.0   5921.0   5874.0   5897.0
4      a2209   DCE  2022-09-02   5866.0   5916.0   5861.0   5891.0
...      ...   ...         ...      ...      ...      ...      ...
3178  zn2308  SHFE  2022-08-29  23820.0  23820.0  23300.0  23305.0
3179  zn2308  SHFE  2022-08-30  23285.0  23285.0  23285.0  23285.0
3180  zn2308  SHFE  2022-08-31  23100.0  23100.0  23100.0  23100.0
3181  zn2308  SHFE  2022-09-01  22905.0  22905.0  22600.0  22600.0
3182  zn2308  SHFE  2022-09-02  22145.0  22235.0  22085.0  22235.0

               7     8     9
0      5963.0000  9404  6465
1      5980.0000  2320  5282
2      5927.0000  2451  4337
3      5883.0000   539  4224
4      5895.0000   406  4209
...          ...   ...   ...
3178  23450.0000     6     9
3179  23285.0000     1     9
3180  23100.0000     1     9
3181  22720.0000     7    12
3182  22155.0000     3    12

[3183 rows x 10 columns]

TypeError: must be real number, not str

In [ ]:

df = pd.read_csv('C:/dev/data/daily_data_220903a.csv', header = None)
df = df.rename(columns={
    '<Date>':'date',
    ' <Time>':'time',
    ' <Open>':'open',
    ' <High>':'high',
    ' <Low>':'low',
    ' <Close>':'close',
    ' <Volume>':'vol',
    })
df['date'] = df['date'].astype('datetime64').dt.strftime('%Y%m%d').astype('int64')
df['time'] = (df['date']-19900000)*10000 + df['time'].str.replace(':', '').str[:-2].astype('int')

BUFFER = WTSBarStruct*len(df)
buffer = BUFFER()

def assign(procession, buffer):
    tuple(map(lambda x: setattr(buffer[x[0]], procession.name, x[1]), enumerate(procession)))


df.apply(assign, buffer=buffer)
print(df)
print(buffer[0].to_dict)
print(buffer[-1].to_dict)

dtHelper.store_bars(barFile="./CFFEX.IF.HOT_m5.bin", firstBar=buffer, count=len(df), period="m5")

In [2]:
from wtpy.wrapper import WtDataHelper
from wtpy.WtCoreDefs import WTSBarStruct, WTSTickStruct
from ctypes import POINTER
from wtpy.SessionMgr import SessionMgr
import pandas as pd

dtHelper = WtDataHelper()


def test_resample():
    # 测试重采样
    sessMgr = SessionMgr()
    sessMgr.load("sessions.json")
    sInfo = sessMgr.getSession("SD0930")
    ret = dtHelper.resample_bars("IC2009.dsb",'m1',5,202001010931,202009181500,sInfo)

In [3]:
from wtpy.apps import WtHotPicker, WtCacheMonExchg, WtCacheMonSS, WtMailNotifier
import datetime
import logging

logging.basicConfig(filename='hotsel.log', level=logging.INFO, filemode="w", 
    format='[%(asctime)s - %(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S')

console = logging.StreamHandler()
console.setLevel(logging.INFO)
# 设置日志打印格式
formatter = logging.Formatter(fmt="[%(asctime)s - %(levelname)s] %(message)s", datefmt='%m-%d %H:%M:%S')
console.setFormatter(formatter)
# 将定义好的console日志handler添加到root logger
logging.getLogger('').addHandler(console)

In [5]:
cacher = WtCacheMonExchg()
picker = WtHotPicker(hotFile="hots.json", secFile="seconds.json")
picker.set_cacher(cacher)

In [10]:
sDate = datetime.datetime.strptime("2019-01-01", '%Y-%m-%d')
eDate = datetime.datetime.strptime("2021-08-21", '%Y-%m-%d') # 可以设置为None，None则自动设置为当前日期
hotRules,secRules = picker.execute_rebuild(sDate, eDate, wait=True)
print(hotRules)
print(secRules)

[08-15 01:28:03 - INFO] [CFFEX]开始拉取20190101数据
[08-15 01:28:03 - INFO] [SHFE]开始拉取20190101数据
[08-15 01:28:03 - INFO] [CZCE]开始拉取20190101数据
[08-15 01:28:03 - INFO] [DCE]开始拉取20190101数据
[08-15 01:28:03 - INFO] [INE]开始拉取20190101数据
[08-15 01:28:04 - INFO] [CFFEX]开始拉取20190102数据

IC1901 1901 [<wtpy.apps.WtHotPicker.DayData object at 0x0000016DB065A9A0>, <wtpy.apps.WtHotPicker.DayData object at 0x0000016DB30206A0>, <wtpy.apps.WtHotPicker.DayData object at 0x0000016DB3020AC0>, <wtpy.apps.WtHotPicker.DayData object at 0x0000016DB1A66E20>]

AttributeError: 'NoneType' object has no attribute 'month'

In [ ]:
def rebuild_hot_rules():
    '''
    重构全部的主力合约切换规则
    '''
    # 从交易所官网拉取行情快照
    cacher = WtCacheMonExchg()  

    # 从datakit落地的行情快照直接读取
    # cacher = WtCacheMonSS("./FUT_DATA/his/snapshot/")

    picker = WtHotPicker(hotFile="hots.json", secFile="seconds.json")
    picker.set_cacher(cacher)

    sDate = datetime.datetime.strptime("2019-01-01", '%Y-%m-%d')
    eDate = datetime.datetime.strptime("2021-08-21", '%Y-%m-%d') # 可以设置为None，None则自动设置为当前日期
    hotRules,secRules = picker.execute_rebuild(sDate, eDate, wait=True)
    print(hotRules)
    print(secRules)

def daily_hot_rules():
    '''
    增量更新主力合约切换规则
    '''
    # 从交易所官网拉取行情快照
    cacher = WtCacheMonExchg()  

    # 从datakit落地的行情快照直接读取
    # cacher = WtCacheMonSS("./FUT_DATA/his/snapshot/")

    picker = WtHotPicker(hotFile="hots.json", secFile="seconds.json")
    picker.set_cacher(cacher)

    # notifier = WtMailNotifier(user="yourmailaddr", pwd="yourmailpwd", host="smtp.exmail.qq.com", port=465, isSSL=True)
    # notifier.add_receiver(name="receiver1", addr="receiver1@qq.com")
    # picker.set_mail_notifier(notifier)

    eDate = datetime.datetime.strptime("2016-03-01", '%Y-%m-%d') # 可以设置为None，None则自动设置为当前日期
    picker.execute_increment(eDate)

rebuild_hot_rules()
input("press enter key to exit\n")